### ISSUE TITLE
Is Icon index necessary?

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/brand-icons#14]
I'm downloading icons of either type, provided in the folder is an icon index file. It is a PDF that goes along with the icons. Is this necessary? I find it might be extra unnecessary data that is downloaded when all the icons are downloaded together.
<img width="711" alt="Screen Shot 2022-05-25 at 3 50 11 PM" src="https://user-images.githubusercontent.com/23122142/170364619-78d00001-2407-48a5-9cf4-7e55ff38b2e6.png">

**Comment by quamsta** [comment]
This is now gone! We merged some things into this repo yesterday that should eliminate the PDFs and the png variants, the functionality of which are now provided by the brand-icon-browser app

**Comment by GaryRidgway** [comment]
THEN NEVERMIND, YEEHAW
